version: "3.9"

services:
  web:
    image: node:16-bullseye
    environment:
      node_port: "3000"
      node_host: "0.0.0.0"
      mysql_host: "db"
      mysql_user: "root"
      mysql_password: "example"
      mysql_database: "test"
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    command: "tail -F /dev/null"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: example
